# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/workspace/vivado/fhm/fhm.srcs/sources_1/bd/arm/ip/arm_axi_dma_0_0/arm_axi_dma_0_0.xci
# IP: The module: 'arm_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/vivado/fhm/fhm.srcs/sources_1/bd/arm/ip/arm_axi_dma_0_0/arm_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/workspace/vivado/fhm/fhm.srcs/sources_1/bd/arm/ip/arm_axi_dma_0_0/arm_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/workspace/vivado/fhm/fhm.srcs/sources_1/bd/arm/ip/arm_axi_dma_0_0/arm_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/workspace/vivado/fhm/fhm.srcs/sources_1/bd/arm/ip/arm_axi_dma_0_0/arm_axi_dma_0_0.xci
# IP: The module: 'arm_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/vivado/fhm/fhm.srcs/sources_1/bd/arm/ip/arm_axi_dma_0_0/arm_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/workspace/vivado/fhm/fhm.srcs/sources_1/bd/arm/ip/arm_axi_dma_0_0/arm_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/workspace/vivado/fhm/fhm.srcs/sources_1/bd/arm/ip/arm_axi_dma_0_0/arm_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
