# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fhm.xdc

# Block Designs: bd/arm/arm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm || ORIG_REF_NAME==arm} -quiet] -quiet

# IP: bd/arm/ip/arm_processing_system7_0_0/arm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_processing_system7_0_0 || ORIG_REF_NAME==arm_processing_system7_0_0} -quiet] -quiet

# XDC: bd/arm/arm_ooc.xdc
